version: '3'
services:
    vending:
        build: .
        ports: 
            - "49160:8080"
        volumes:
            - ".:/usr/src/app"
            - exclude:/usr/src/app/node_modules/
        network_mode: bridge

volumes:
    exclude: